### ISSUE TITLE
Add a send or transfer command for GO

### ISSUE THREAD

**Issue by treeder** [gochain-io/web3#62]
Use case is that if you have a funded account, but need to fund others for testing, etc., this would be very helpful.

```sh
web3 account create
web3 transfer 50 GO to 0xABC
```

**Comment by jmank88** [comment]
`web3 send -to 0xa 100go`
`web3 send -to 0xb -gas-price 5gwei 10eth`
Maybe value or amount being a flag would make it more readable.

**Comment by jmank88** [comment]
Units to support:
- go, eth, ether
- milli, finney
- micro, szabo
- nano, gwei, shannon
- pico, mwei, lovelace
- femto, kwei, babbage
- atto, wei

Should a lack of units default to something? If we are going to print out everything for confirmation first, then I think a default makes sense. Otherwise maybe it should be explicit to prevent mistakes.

Should gas price default to a certain value? Or use whatever `suggest` says?

**Comment by treeder** [comment]
For gas, might as well use what it suggests as default.

For units, I think the only ones that really matter are (with slightly modified names):

* go, eth
* nanogo, gwei
* attogo, wei

If they want some other unit, they can add or remove 0s from the above.
